Feat : Implémentation de l'affichage de tous les livres
gillout/book-store pull request #1
Opened 2020-10-15 10:45 UTC by gillout

Pour l'instant, j'ai trouvé une autre façon de faire. J'ai créée un tableau dans le manager (il contient un tableau pour chaque livre).
La méthode "all" du contrôleur va chercher les livres.
J'ai essayé de faire un for et aussi un foreach en plus du foreach déjà présent dans la méthode.
Cela pour ne pas avoir à faire 4 lignes : self::BOOKS....., mais je n'ai pas trouvé comment faire, à cause du constructeur de la classe Book.

2020-10-16 22:13 UTC, matthieuaudemard requested changes
C'est bien ! Juste quelques petites modifs à apporter. :)

2020-10-16 22:13 UTC, matthieuaudemard commented on public/index.php
>  require_once dirname(__DIR__) . '/vendor/autoload.php';
Ca marche peut être je n'ai pas essayé, mais je pense qu'il serait mieux de mettre ton require_once autoloder en toute 1ère instruction du fichier pour la simple et bonne raison que cet autoloader va te permettre de charger tes classes.

2020-10-16 22:13 UTC, matthieuaudemard commented on src/app/controller/BookController.php
> +        require_once ROOT_DIR . 'index.html';
Initialement ce que je pensais c'est que par défaut (sans autre paramètre) on affiche all. Donc index affiche all, mais tu as peut être quelque chose de prévu pour index

2020-10-16 22:13 UTC, matthieuaudemard commented on src/app/manager/BookManager.php
> +        foreach (self::BOOKS as $i => $book) {
C'est une solution, mais peut être pas la meilleure. Tu crées un tableau static pour au final créer un autre tableau ça fait bcp d'opération. Je pense que la solution la plus simple serait de déclarer un attribut (non static) dans ta classe et de remplir ce tableau d'objets books créé à la volée sans utiliser ton tableau BOOKS.

2020-10-16 22:13 UTC, matthieuaudemard commented on src/app/model/Book.php
> +    public function __construct($id, $nom, $editeur, $prix)
Dans le but d'utiliser PDO un peu plus tard pour la gestion de PDO, il va être utile de modifier un peu ce constructeur. En effet, PDO a besoin de pouvoir utiliser un constructeur sans paramètre. Je pense que tu peux mettre des paramètres par défaut dans celui que tu as créé pour que PDO puisse lancer `new Book()`sans que ça pose de soucis.

2020-10-16 22:13 UTC, matthieuaudemard commented on public/style.css
> +* {
Tu as encore besoin de ce css ?

2020-10-17 07:36 UTC, gillout commented on public/index.php
>  require_once dirname(__DIR__) . '/vendor/autoload.php';
Du coup, je n'ai plus besoin du use pour la classe Router ?

2020-10-17 07:39 UTC, gillout commented on src/app/controller/BookController.php
> +        require_once ROOT_DIR . 'index.html';
Rien de prévu pour l'instant, c'était juste pour que tu puisses voir que j'ai bien respecter la maquette et aussi cela me permettait de l'afficher.

2020-10-17 07:46 UTC, gillout commented on src/app/controller/BookController.php
> +        require_once ROOT_DIR . 'index.html';
En y réfléchissant, si j'ai bien une idée, on en parlera mais probablement pas de suite ;)

2020-10-17 07:49 UTC, gillout commented on src/app/controller/BookController.php
> +        require_once ROOT_DIR . 'index.html';
Du coup je modifie la route par défaut sur la fonction all() et je laisse la fonction index pour l'instant comme elle est.

2020-10-17 08:15 UTC, gillout commented on src/app/manager/BookManager.php
> +        foreach (self::BOOKS as $i => $book) {
En fait, oui je sais, mais j'avais fait ça en attendant la base ou que tu me montres comment faire si c'est possible un tableau d'objets dans le manager.
Au début, j'avais tout fait dans la fonction all() du manager mais ensuite je me suis dit que j'allais faire comme simuler d'aller chercher des infos et créer le tableau d'objets.

2020-10-17 08:20 UTC, gillout commented on public/style.css
> +* {
Oui, je n'utilise pas toutes les classes de Bootstrap comme dans la maquette.

2020-10-17 08:21 UTC, gillout commented on src/app/model/Book.php
> +    public function __construct($id, $nom, $editeur, $prix)
Je ne vois pas trop quoi mettre en paramètres par défaut.

2020-10-17 08:55 UTC, gillout commented on public/style.css
> +* {
En fait, je n'utilise pas du tout Bootstrap sur ce projet.

2020-10-17 10:32 UTC, gillout commented on src/app/manager/BookManager.php
> +        foreach (self::BOOKS as $i => $book) {
Je ne vois pas exactement comment faire.

2020-10-17 13:04 UTC, matthieuaudemard requested changes
Juste une petite modif et ça sera top ;)

2020-10-17 13:04 UTC, matthieuaudemard commented on src/app/back/view/all.php
> +<?php
Potentiellement ce fichier sera utilisé dans plusieurs contextes et pas seulement celui de 'all'. Je pense que tu peux renommer ce fichier en list.php pour par exemple l'utiliser dans la recherche.

2020-10-23 17:10 UTC, closed without merging