Feat : Ajoute la recherche dynamique
gillout/book-store pull request #14
Opened 2020-12-05 18:09 UTC by gillout

2020-12-05 20:04 UTC, matthieuaudemard requested changes
C'est bien 👍 🍰 🍬 ⛅ 🎈  😉 
Je pense que tu as juste oublié un return.
J'ai eu une idée qui pourrait éventuellement simplifier les choses, libre à toi de l'implémenter ou pas :
- tu peux utiliser la fonction [array_intersect_key](https://www.php.net/manual/fr/function.array-intersect-key.php) qui te permet de ne récupérer que l'intersection des clés des tableaux en paramètres. Ainsi tu peux créer une méthode privée `private function extractParameters(array $criterias, array $arrayAssocs): array`. Cette méthode va filtrer ton $criterias en ne gardant que les clés qui sont présentes dans `$arrayAssocs` et renommer les clés de `$criterias`  à patir des valeurs de `$filters` (ex: $arrayAssocs = ['bookId' => 'id', 'bookName' => 'name', 'bookPublisher' => 'publisher']).

- tu crées par la suite une méthode privée `private function generateFilterRequest(array $filters): string` dans laquelle tu as juste à faire un `foreach` (voire un `array_map` si tu te sens l'âme d'un guerrier 😉) sur le tableau et qui va te générer tes parties de requête, il te restera juste à faire ton join.

- tu crées une autre méthode privée `private function generateFilterParameters(array $filters): array` qui te crées à partir du tableau `$filters` le tableau de paramètres à fournir à `PDOStatement::execute`.

pour résumer : 
```php
$arrayAssocs =  ['bookId' => 'id', 'bookName' => 'name', 'bookPublisher' => 'publisher'];
$filters = $this->extractParameters($criterias, $arrayAssocs);
$request = $this->generateFilterRequest($filters);
$param = $this->generateFilterParameters;
$this->db->prepare($request);
$stmt->exexute($params);
```

Si tu décide de mettre en place cette solution tu peux commit un message : Refact: modifie la méthode de recherche de livres par critères (par exemple). Ca illustre bien ce qu'est une refactorisation.

2020-12-05 20:04 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            $this->all();
Je pense qu'il manque un `return` ici

2020-12-05 20:04 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +        } else {
du coup si il y a un return, plus besoin de mettre `else`

2020-12-05 20:14 UTC, gillout commented on src/app/back/manager/BookManager.php
> +            $this->all();
Non, il est dans la fonction all() :
/**
     * Renvoie tous les livres
     * @return Book[]
     */
    public function all(): array
    {
        $stmt = $this->db->query('SELECT * FROM book');
        return $stmt->fetchAll(PDO::FETCH_CLASS, Book::class);
    }
;)

2020-12-05 20:17 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            $this->all();
Alors certes il est dans la fonction all(), mais du coup dans search() ça te retourne rien. t'es obligé de mettre `return $this->all()`

2020-12-05 20:31 UTC, gillout commented on src/app/back/manager/BookManager.php
> +            $this->all();
Ok, pourtant ça marchait bien.

2020-12-06 15:48 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            $this->all();
Oui ça marche parce que dans le cas ou tu passes dans ton `if` tu executes quand même :
```php
$req = 'SELECT * FROM book';  // cf ligne 133
$reqParts = [];
$params = [];
$stmt = $this->db->prepare($req . join(' AND ', $reqParts)); // cf ligne 157
...
```
mais du coup ton `if` sert à rien parce que tu executes quand même le code que tu voulais pas executer et ton `$this->all();` n'est récupéré nul part et part dans la nature.

2020-12-13 16:06 UTC, matthieuaudemard approved these changes
good job 👍

2020-12-13 16:21 UTC, merged