Research
gillout/book-store pull request #2
Opened 2020-10-23 17:12 UTC by gillout

Cela fonctionne mais il y a surement bien plus opti. ;)

2020-10-24 19:17 UTC, matthieuaudemard commented
Salut Gilles, je pense avoir oublié quelque chose dans mes explications de gestion des branches git et les différents ajouts. Je te mets une image d'un workflow git classique pour illustrer mes propos :
![git-flow-before](https://user-images.githubusercontent.com/4210719/97090903-0dc62080-1638-11eb-9044-25a8a245759d.jpg)
Concrètement on a 2 branches "persistantes" : **master** et **develop**.
- **master** correspond à la version stable de ton programme. Dans notre exemple, on peut considérer que master contiendra la version entièrement fonctionnelle de notre back (celle ou l'on pourra ajouter, supprimer, rechercher, modifier ....).
- **develop** est une branche importante car elle permet d'accumuler une par une les nouvelles fonctionnalitées (features). Ca nous permet d'isoler nos développements en cours  de l'application "stable" (celle qui est sur master) dans le but de cloturer le périmètre de la demande (dans notre cas la demande c'est de fournir un back - site d'administration - de notre application qui permette de faire les opérations de CRUD).

Le 3ème type de branche affiché dans ce schéma (**feature-x**) correspond à une branche temporaire qui contient une et une seule fonctionnalité ou correction.

On l'associe en général à un ticket dans un logiciel de gestion de ticket ou le kanban de github, tu peux d'ailleurs essayer de le créer (onglet projects) pour la finalisation de ton back en ajoutant toi même les différentes fonctionnalités que tu as déjà implémentées + celles qui te reste à mettre en place ; je te conseille de choisir le template '_automated kanban with reviews_'.

Pour cette fois, on va se contenter de merger sur **master**, mais pour la prochaine fonctionnalité je te laisserai créer ne branche **develop** à partir de master, puis une branche à partir de **develop** correspondant à la fonctionnalité que tu souhaites développer .

2020-10-24 20:40 UTC, matthieuaudemard requested changes
Je t'ai proposé quelques améliorations. Hésite pas à répondre à mes commentaires si tu as besoin de plus d'infos.

Bon courage ;)

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/controller/BookController.php
> +    public function search($researchs): void
Pense à préciser que $researchs est un tableau. Au passage ça s'écrit researchEs.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/controller/BookController.php
> +        foreach ($researchs as $key => $research) {
Ok tu veux renommer les clés, c'est comme tu veux, mais quelle utilité ?

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +                if ($criteria['Id'] == $book->getId()) {
C'est mieux de mettre `===` en général. Pour le cas des id je veux bien comprendre parce qu'on compare un `string` à un `int`. L'autre possibilité serait de comparer la valeur entière de criteria['Id] à $book->getId().

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +                $search = '/' . $criteria['Name'] . '/i';
C'est une pratique à laquelle tu devrais t'entrainer : ne créer une variable que si nécessaire : 
> Ne créer une variable que si on l'utilise au moins deux fois.

Essaye de ne pas utiliser cette variable `$search`.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +    public function search(array $criteria): ?array
Attention, c'est une pratique dangereuse de retourner `null` à la place d'un tableau. Préfère retourner un tableau vide.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +     * @param array $criteria
Tu devrais donner un commentaire pour ce paramètre $criteria pour préciser au développeur qui utiliserait cette méthode de quelle type de tableau il s'agit et quelles données mettre dans ce tableau.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +        foreach ($results as $id) {
Je comprend pas bien l'utilité de cette boucle. Est-elle vraiment utile ? Si je comprend bien tu re-recherches les livres dans le tableau de livre alors que tu les as déjà dans `$result`.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +        return $books;
Globalement, la complexité de cette méthode est trop élevée (6 boucles + un array_unique). Tu peux essayer de la refaire en utilisant une seule boucle. Je te donnes le début, à toi de compléter.
```php
$result = [];
foreach ($this->books as $book) {
...
}
return $result;
```
Si tu n'y arrives pas je te donnerais la solution.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                <figure>
Je suis pas certain que la balise `<figure>` soit appropriée ici. Personnellement j'utilise plutôt figure avec une `<figcaption>` (cf. https://developer.mozilla.org/fr/docs/Web/HTML/Element/figure). A toi de voir.

2020-10-24 20:40 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
Dans le contexte de recherche il serait très intéressant de pouvoir afficher les valeurs de soumisent.

2020-10-26 09:03 UTC, gillout commented on src/app/back/controller/BookController.php
> +        foreach ($researchs as $key => $research) {
En fait, je pensais que peut-être il y aurait moyen de simplifier les 4 if dans la fonction search du manager par un truc un peu comme hydrate mais ça change pas grand chose en effet.

2020-10-26 09:04 UTC, gillout commented on src/app/back/controller/BookController.php
> +    public function search($researchs): void
En fait, c'est pas un bug, j'avais pas compris ça comme ça.
Je pensais qu'on voulait afficher tous les livres dont au moins un des critères était passé en paramètres.
Mais ok, je vais essayer de faire ça.

2020-10-26 09:12 UTC, gillout commented on src/app/back/manager/BookManager.php
> +                if ($criteria['Id'] == $book->getId()) {
Oui, j'avais pensé à faire intval pour $criteria[$id] mais je ne sais pas si c'est vraiment intéressant.

2020-10-26 09:15 UTC, gillout commented on src/app/back/manager/BookManager.php
> +                if ($criteria['Id'] == $book->getId()) {
Est-ce mieux d'ajouter un int et de faire avec === ou juste == ?

2020-10-26 09:20 UTC, gillout commented on src/app/back/manager/BookManager.php
> +                $search = '/' . $criteria['Name'] . '/i';
J'avoue que je n'ai pas essayer de mettre l'ensemble  '/' . $criteria['Name'] . '/i' dans le preg_match et j'ai pensé que ce n'était pas très lisible.
De toutes façons c'était juste pour essayer les 2 possibilités : preg_match et strpos.
Comme il semblerait que strpos est plus adapté ou plus performant que preg_match dans ce cas, j'avais prévu après la review de mettre strpos pour Name et Publisher. ;)

2020-10-26 09:23 UTC, gillout commented on src/app/back/manager/BookManager.php
> +    public function search(array $criteria): ?array
Ok

2020-10-26 09:37 UTC, gillout commented on src/app/back/manager/BookManager.php
> +        foreach ($results as $id) {
Avant la boucle, j'ai les ids mais pas les objets livres.

2020-10-26 09:40 UTC, gillout commented on src/app/back/manager/BookManager.php
> +        return $books;
C'est justement ce que je voulais essayer de faire dont je te parle dans un des premiers commentaires en haut de la review. ;)

2020-10-26 09:44 UTC, gillout commented on src/app/back/view/template.php
> +                <figure>
Plutôt que d'utiliser des divs comme beaucoup le font à tout va.
Figure est aussi de type bloc et est bien adapté pour encadrer une image.
A vérifier pour savoir si c'est vraiment une bonne pratique ou non.

2020-10-26 12:32 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +                if ($criteria['Id'] == $book->getId()) {
> Si vous comparez un nombre avec une chaîne ou bien que la comparaison implique des chaînes numériques, alors chaque chaîne sera convertie en un nombre et la comparaison sera effectuée numériquement.
https://www.php.net/manual/fr/language.operators.comparison.php

Au final ça revient au même, à la différence que php doit au préalable déterminer qu'il s'agit de chaînes numériques ce qui va coûter des ressources. Je pense donc que lancer directement `(int) $criteria['Id'] === $book->getId()` est ce qu'il y a de plus opti.

2020-10-26 12:33 UTC, matthieuaudemard commented on src/app/back/controller/BookController.php
> +    public function search($researchs): void
Ca va rajouter un peu de complexité, mais je pense que ça correspond mieux à la réalité.

2020-10-26 12:40 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                <figure>
Y'a une forte notion de sémantique en HTML. L'idée c'est d'adapter les balises à utiliser en fonction de la nature de ce qu'elles englobent.
Pour `<figure>` j'entend plus "illustration" ou élément qui apporte un plus à la compréhension du sujet ou l'illustre. Dans ce cas il s'agit simplement d'un logo qui de surcroît n'est même pas une image mais un fontawesome ... à savoir qu'un fontawesome n'est pas une image mais un caractère utf8 (comme les emoji etc...). Libre à toi cependant de l'interpréter comme tu veux ;)

2020-10-26 12:41 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
Si la tâche te parait trop longue, laisse cette fonctionnalité de côté tu créeras une branche nouvelle branche feature pour la mettre en place.

2020-10-26 14:36 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +        return $books;
En fait du coup tu vas avoir une grosse condition pour savoir si tu dois ajouter ton livre dans la liste et c'est même toute la difficulté de la chose de formaliser cette condition d'ajout.

2020-10-26 19:38 UTC, gillout commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
J'ai fait en sorte que les valeurs de recherche restent dans le formulaire à l'affichage du résultat.

2020-10-26 21:33 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
Je ne le vois pas ? Tu l'as push ?

2020-10-27 11:02 UTC, gillout commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
Non, pas encore push.

2020-10-27 11:05 UTC, gillout commented on src/app/back/manager/BookManager.php
> +        return $books;
Je ne vois pas trop comment faire pour rassembler toutes les conditions et faire en sorte d'avoir à la fois le résultat si plusieurs
paramètres pour un même livre ou une seule pour chacun, sauf de faire un stock de conditions.
Je pensais à un système de compteur mais je n'arrive pas à le concrétiser.

2020-10-27 11:09 UTC, gillout commented on src/app/back/manager/BookManager.php
> +        return $books;
Je push déjà ce que j'ai fait pour que tu vois un peu et en même temps pour la partie concernant le fait qu'on puisse voir les critères de la recherche effectuée.

2020-10-27 11:11 UTC, gillout commented on src/app/back/view/template.php
> +                <input id="input-id" type="text" name="bookId" autocomplete="off" placeholder="ID">
Voilà, maintenant c'est push. ;)

2020-11-01 10:08 UTC, matthieuaudemard requested changes
Encore quelques petites modifications :)

2020-11-01 10:08 UTC, matthieuaudemard commented on src/app/back/controller/BookController.php
> +    public function search(array $researchEs): void
Ah pardon :D Si j'ai mis 'E' majuscule c'etait juste pour le mettre en évidence

2020-11-01 10:08 UTC, matthieuaudemard commented on src/app/back/view/template.php
> +                       <?= isset($criteria) && array_key_exists('Id', $criteria) ?
Comme tu utilises plusieurs fois la fonction `isset($criteria)` tu peux créer un booléen `$displayCriteria = isset($criteria)` pour l'utiliser dans chaque champ de recherche : `<?= $displayCriteria && array_key_exists('Id', $criteria) ? ... `. Ca simplifie la lisibilité et optimise un peu . Sinon c'est bien 👍

2020-11-01 10:08 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +                if (intval($criteria['Id']) === $book->getId()) {
Pour information, il est aussi possible de "caster" en int à l'aide de l'opérateur de cast : `(int)` plutôt que d'utiliser `intval()` la syntaxe est simple : `(int) $criteria['Id'] === $book->getId()`. On appelle ça une opération de transtypage ou casting en anglais. Apparement à partir d'une certaine version de php les perfs sont équivalentes. Peut être que ça peut aider à la lisibilité, mais ça c'est à toi de voir.

Au passage c'est aussi valable pour float ;)

2020-11-01 10:08 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            foreach ($book as $key => $valeur) {
Tu n'as pas besoin de boucle imbriquée. Globalement, tu dois trouver une condition en compilant tes `$criteria` qui te permette de savoir si tu dois ajouter ou non un livre à la liste de résultat. Pour faire simple tu gardes un livre si :
- le critère C1 n'est pas dans `$criteria` ou le critère C1 est dans le tableau et il correspond au paramètre du livre.
- et qu'il vérifie les mêmes conditions pour les autres critères Cn où Cn correspond aux autres critères.

2020-11-01 11:02 UTC, matthieuaudemard approved these changes

2020-11-01 11:03 UTC, merged