Add
gillout/book-store pull request #5
Opened 2020-11-04 21:44 UTC by gillout

2020-11-04 23:54 UTC, matthieuaudemard requested changes
Ca semble assez cohérent au niveau des requête. Je t'ai fait une suggestion purement esthétique au niveau du passage de ton tableau dans la méthode execute.

Essaye de mettre en place le passage des tableaux post et get dans le routeur puis je pense que tu devras faire la [fiche de gestion des 3 boutons](https://github.com/gillout/book-store/projects/1#card-48477055).

2020-11-04 23:54 UTC, matthieuaudemard commented on public/index.php
> +$router = new Router(array_merge($_GET, $_POST), $db);
Mauvaise idée de merge les 2 parce que potentiellement tu peux avoir une clé identique dans chacun des 2 tableaux. Il vaudrait mieux retoucher la classe router pour qu'elle ait 2 attributs (voire 3) :
- le tableau get
- le tableau post
- et eventuellement le tableau session

2020-11-04 23:54 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            ':price' => $book->getPrice()]);
C'est peut être plus lisible d'écrire : 
```suggestion
        $result = $stmt->execute([
            ':id' => $book->getId(),
            ':name' => $book->getName(),
            ':publisher' => $book->getPublisher(),
            ':price' => $book->getPrice()
        ]);
```

2020-11-05 07:38 UTC, gillout commented on src/app/back/manager/BookManager.php
> +            ':price' => $book->getPrice()]);
Oui, en effet, c'était comme ça avant. J'ai du faire une fausse manip.

2020-11-06 08:34 UTC, matthieuaudemard commented on src/app/back/manager/BookManager.php
> +            ':price' => $book->getPrice()]);
Tu l'as commit ? Je ne le vois pas !

2020-11-06 18:20 UTC, matthieuaudemard approved these changes
OK c'est tout bon pour moi, bien joué ;)

2020-11-07 11:41 UTC, matthieuaudemard approved these changes

2020-11-07 11:43 UTC, merged